version: '3'
services:


#  client:
#    build:
#      dockerfile: Dockerfile
#      context: ./bmsv2
#    ports:
#      - "3001:3000"
#    volumes:
#      - ./bmsv2:/app
#    logging:
#      driver: none

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      kafka-0:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
    networks:
      - api-gateway-network
      - kafka_network
      - auth-network
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app



  # user-db:
  #   image: postgres
  #   restart: always
  #   networks:
  #     - auth-network
  #   environment:
  #     POSTGRES_DB: userdb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - user_data:/var/lib/postgresql/data

  # auth-service:
  #   build:
  #     context: ./auth
  #     dockerfile: Dockerfile
  #   restart: always
  #   networks:
  #     - auth-network
  #   depends_on:
  #     - user-db
  #   environment:
  #     TYPEORM_HOST: user-db
  #     TYPEORM_PORT: 5432
  #     TYPEORM_USERNAME: user
  #     TYPEORM_PASSWORD: password
  #     TYPEORM_DATABASE: userdb
  #   volumes:
  #     - ./auth:/app

  # product-db:
  #   image: postgres
  #   restart: always
  #   networks:
  #     - product-network
  #   environment:
  #     POSTGRES_DB: productdb
  #     POSTGRES_USER: productuser
  #     POSTGRES_PASSWORD: productpassword
  #     POSTGRESQL_SYNCHRONOUS_COMMIT_MODE: on
  #     POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 1
  #   volumes:
  #     - product_data:/var/lib/postgresql/data

  # product-db-slave:
  #   image: postgres
  #   restart: always
  #   networks:
  #     - product-network
  #   environment:
  #     POSTGRESQL_REPLICATION_MODE: slave
  #     POSTGRES_DB: productdb
  #     POSTGRESQL_MASTER_HOST: product-db
  #     POSTGRESQL_MASTER_PORT_NUMBER: 5432
  #     POSTGRES_USER: productuser
  #     POSTGRES_PASSWORD: productpassword
  #   volumes:
  #     - product_data:/var/lib/postgresql/data

  # product-service:
  #   build:
  #     context: ./products
  #     dockerfile: Dockerfile
  #   restart: always
  #   networks:
  #     - product-network
  #     - api-gateway-network
  #     - kafka_network
  #   depends_on:
  #     - product-db
  #     - product-db-slave
  #   environment:
  #     TYPEORM_HOST: product-db
  #     TYPEORM_HOST_SLAVE: product-db-slave
  #     TYPEORM_PORT: 5432
  #     TYPEORM_USERNAME: productuser
  #     TYPEORM_PASSWORD: productpassword
  #     TYPEORM_DATABASE: productdb
  #   volumes:
  #     - ./products:/app
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro





networks:
  api-gateway-network:
  kafka_network:
  auth-network:
  # product-network:
  # order-network:
  # image-service-network:


volumes:
  user_data:
    driver: local
  data:
    driver: local

