version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: gateway-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - connectfy-file-service-network

volumes:
  minio_data:

networks:
  connectfy-file-service-network:
    external: true
  kafka_network:
    external: true
