services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - connectfy-redis-network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-ui:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - connectfy-redis-network
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  connectfy-redis-network:
    external: true
